kind: Service
apiVersion: v1
metadata:
  name: thing-api-observability
spec:
  selector:
    app: thing-api-observability
    runtime: dotnet
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP