apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#helm inspect chart oci://041371538652.dkr.ecr.ap-southeast-2.amazonaws.com/foundations-test
helmCharts:
- name:  foundations-test
  repo: oci://041371538652.dkr.ecr.ap-southeast-2.amazonaws.com
  version: 1.0.0
 
  releaseName: goldenpath
  valuesFile: default-helm-values.yaml

  includeCRDs: false
  valuesInline:
    someDefaults:
      eula: true
      fruit: banana
      param1: foo
      param2: bar
